# Generated by Django 4.2.20 on 2025-05-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('brass', 'Brass'), ('kg', 'Kilograms'), ('ton', 'Tons')], default='pcs', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gsb_applicable', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='item',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.buildingmaterial'),
            preserve_default=False,
        ),
    ]
